language: java
install:
  - "gradle check"
script:
  - "src/test/java/scripts/TestExamples.java"
addons:
  browserstack:
    username: "csmidev1"
    access_key: "XAmfaftDn3ywKgun2LpZ"
    app_path: "MyFrameworkGradlSeleniumAutomation"